version: "3.8"
services:
  firestore:
    build:
      context: .
      dockerfile: Dockerfile.firestore
    ports:
      - 8000:8000
    volumes:
      # - .cache/firebase/emulators/:/app/.cache/firebase/emulators/
      - .:/app
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PROJECT_ID: foo
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8000
    volumes:
      - .:/go/src/app

